# Generated by Django 4.2.7 on 2024-06-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=10)),
                ('solicitante', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=13)),
            ],
        ),
    ]
